name: vetmanager_internship_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.4
  dio: ^5.8.0+1
  flutter_secure_storage: ^9.2.4
  injectable: ^2.5.0
  build_runner: ^2.4.15
  injectable_generator: ^2.7.0
  get_it: ^8.0.3
  retrofit: ^4.4.2
  retrofit_generator: ^9.1.2
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  freezed: ^3.0.4
  freezed_annotation: ^3.0.0
  flutter_bloc: ^9.1.0
  logging: ^1.3.0
  stack_trace: ^1.12.0
  clock: ^1.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true




